### ISSUE TITLE
Verbose output when time entries are not synchronizing correctly.

### ISSUE THREAD

**Issue by mwasilewski-in** [ozguryazilimas/redmine_toggl#8]
When any problem would apear during synchonization task, there is hard to find a problematic entry.
Below is an example of log, when toggl is syncrhonize an entry after issue is closed. It's hardly to find which user, issue or entry has a problem. 

```RAILS_ENV=production bundle exec rake toggl:sync_time_entries["2024-04-15 00:01","2024-04-18 23:59"] --trace
** Invoke toggl:sync_time_entries (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute toggl:sync_time_entries
rake aborted!
Validation failed: Issue is a closed issue. You are not allowed to log time at it.
/opt/redmine-4.1.5/plugins/redmine_toggl/lib/tasks/toggl.rake:185:in `block (2 levels) in format_toggl_service_errors'
/opt/redmine-4.1.5/plugins/redmine_toggl/lib/tasks/toggl.rake:184:in `each'
/opt/redmine-4.1.5/plugins/redmine_toggl/lib/tasks/toggl.rake:184:in `block in format_toggl_service_errors'
/opt/redmine-4.1.5/plugins/redmine_toggl/lib/tasks/toggl.rake:183:in `each'
/opt/redmine-4.1.5/plugins/redmine_toggl/lib/tasks/toggl.rake:183:in `format_toggl_service_errors'
/opt/redmine-4.1.5/plugins/redmine_toggl/lib/tasks/toggl.rake:10:in `block (2 levels) in <top (required)>'
/opt/redmine-4.1.5/vendor/cache/ruby/2.6.0/gems/rake-13.0.6/lib/rake/task.rb:279:in `block in execute'
/opt/redmine-4.1.5/vendor/cache/ruby/2.6.0/gems/rake-13.0.6/lib/rake/task.rb:279:in `each'
/opt/redmine-4.1.5/vendor/cache/ruby/2.6.0/gems/rake-13.0.6/lib/rake/task.rb:279:in `execute'
/opt/redmine-4.1.5/vendor/cache/ruby/2.6.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/var/www/.rbenv/versions/2.6.6/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/opt/redmine-4.1.5/vendor/cache/ruby/2.6.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/opt/redmine-4.1.5/vendor/cache/ruby/2.6.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/opt/redmine-4.1.5/vendor/cache/ruby/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/opt/redmine-4.1.5/vendor/cache/ruby/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/opt/redmine-4.1.5/vendor/cache/ruby/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/opt/redmine-4.1.5/vendor/cache/ruby/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/opt/redmine-4.1.5/vendor/cache/ruby/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/opt/redmine-4.1.5/vendor/cache/ruby/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/opt/redmine-4.1.5/vendor/cache/ruby/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/opt/redmine-4.1.5/vendor/cache/ruby/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/redmine-4.1.5/vendor/cache/ruby/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/opt/redmine-4.1.5/vendor/cache/ruby/2.6.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/redmine-4.1.5/vendor/cache/ruby/2.6.0/bin/rake:23:in `load'
/opt/redmine-4.1.5/vendor/cache/ruby/2.6.0/bin/rake:23:in `<top (required)>'
/var/www/.rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
/var/www/.rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
/var/www/.rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
/var/www/.rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
/var/www/.rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/www/.rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/www/.rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/www/.rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
/var/www/.rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/www/.rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
/var/www/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
/var/www/.rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/var/www/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
/var/www/.rbenv/versions/2.6.6/bin/bundle:23:in `load'
/var/www/.rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
Tasks: TOP => toggl:sync_time_entries
```

**Comment by zaburt** [comment]
We had some work on this, it is completed now, we show nicer error messages on rake task output. Note that you should not have "--trace" in the command.
